[tox]
envlist = py,lint

[testenv]
# LIB/INCLUDE/LIBPATH: MSVC vcvars environment, needed when cmake uses NMake/Ninja on Windows
passenv =
    APPVEYOR
    GITHUB_WORKFLOW
    CGET_VERBOSE
    LIB
    INCLUDE
    LIBPATH
    CGET_USE_SYMLINKS
deps = 
    -r{toxinidir}/requirements.txt
    coverage
    pytest
    pytest-cov
    pytest-timeout
    pytest-xdist
commands =
    py.test -n {env:TOX_PYTEST_NTHREADS:auto} --basetemp={envtmpdir} --timeout=1200 --cov-config=tox.ini --cov=cget --cov-report=html {posargs}

[testenv:lint]
deps = 
    -r{toxinidir}/requirements.txt
    pyflakes 
commands = pyflakes {toxinidir}/cget

[run]
branch = True
