name: cget

on: [push, pull_request]

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
  test:
    runs-on: ${{ matrix.platform }}
    container: ${{ matrix.container || '' }}
    strategy:
      matrix:
        platform:
          - ubuntu-24.04
        python-version: ['3.8', '3.9', '3.10', '3.12']
        include:
          - platform: ubuntu-24.04
            python-version: '3.6'
            container: python:3.6-slim
          - platform: ubuntu-24.04
            python-version: '3.7'
            container: python:3.7-slim
          - platform: macos-15
            python-version: '3.12'
          - platform: windows-2025
            python-version: '3.12'

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ !matrix.container }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup msbuild
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      continue-on-error: true
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: 3.31.0
    - name: Install build tools
      if: matrix.container
      run: |
        apt-get update
        apt-get install -y make gcc g++ pkg-config
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install tox
    - name: Install pkg-config (Windows)
      if: runner.os == 'Windows'
      run: choco install pkgconfiglite -y
    - name: Test with tox
      run: tox -e py,lint
      env:
        CGET_VERBOSE: 1
